import pandas as pd
from sqlalchemy import text

from app.database import engine
from app.logger import logger


def load_locations() -> None:
    """
    Extract unique locations from raw_jobs and
    load them into the locations table.
    """

    logger.info("Loading locations table...")

    query = """
        SELECT DISTINCT
            TRIM(job_location) AS job_location,
            TRIM(job_country) AS job_country,
            TRIM(search_location) AS search_location
        FROM raw_jobs
    """

    locations = pd.read_sql(query, engine)

    # Replace empty strings with NULL
    locations = locations.replace(r'^\s*$', None, regex=True)

    # Remove duplicates generated by NULL values
    locations = locations.drop_duplicates()

    logger.info(
        f"Locations extracted: {len(locations)}"
    )

    with engine.begin() as connection:

        connection.execute(
            text(
                "TRUNCATE TABLE locations RESTART IDENTITY CASCADE;"
            )
        )

    locations.to_sql(
        "locations",
        engine,
        if_exists="append",
        index=False,
        method="multi",
        chunksize=5000,
    )

    logger.info(
        f"Locations loaded successfully: {len(locations)}"
    )